CREATE TABLE public.favorites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  film_id UUID NOT NULL REFERENCES public.films(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (user_id, film_id)
);

ALTER TABLE public.favorites ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own favorites."
ON public.favorites FOR SELECT
USING ( auth.uid() = user_id );

CREATE POLICY "Users can insert their own favorites."
ON public.favorites FOR INSERT
WITH CHECK ( auth.uid() = user_id );

CREATE POLICY "Users can delete their own favorites."
ON public.favorites FOR DELETE
USING ( auth.uid() = user_id );