ALTER TABLE public.platform_settings
ADD COLUMN IF NOT EXISTS platform_name TEXT DEFAULT 'UniShorts',
ADD COLUMN IF NOT EXISTS platform_description TEXT,
ADD COLUMN IF NOT EXISTS default_language TEXT DEFAULT 'en',
ADD COLUMN IF NOT EXISTS timezone TEXT DEFAULT 'UTC',
ADD COLUMN IF NOT EXISTS maintenance_mode BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS maintenance_message TEXT,
ADD COLUMN IF NOT EXISTS favicon_url TEXT,
ADD COLUMN IF NOT EXISTS secondary_color TEXT DEFAULT '#64748b',
ADD COLUMN IF NOT EXISTS background_color TEXT DEFAULT '#ffffff',
ADD COLUMN IF NOT EXISTS theme_mode TEXT DEFAULT 'system',
ADD COLUMN IF NOT EXISTS footer_copyright TEXT,
ADD COLUMN IF NOT EXISTS enable_2fa BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS failed_login_limit INTEGER DEFAULT 5;