-- Drop the table if it exists to ensure a clean slate
DROP TABLE IF EXISTS public.email_templates;

-- Create the table again with a fresh structure
CREATE TABLE public.email_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  subject text NOT NULL,
  body text NOT NULL,
  created_at timestamp with time zone NULL DEFAULT now(),
  updated_at timestamp with time zone NULL DEFAULT now(),
  is_enabled boolean NOT NULL DEFAULT true,
  CONSTRAINT email_templates_pkey PRIMARY KEY (id),
  CONSTRAINT email_templates_name_key UNIQUE (name)
);

-- Insert all 10 required email templates
INSERT INTO public.email_templates (name, subject, body) VALUES
('Account Confirmation', 'Confirm your UniShorts Account | قم بتأكيد حسابك', '{{> base_email_template subject="Account Confirmation" preheader="Please confirm your email address to get started." content_ar="<p style=''margin: 0 0 16px; font-weight: 700; font-size: 20px; color: #000000;''>أهلاً بك، {{user_name}}!</p><p style=''margin: 0 0 24px; font-size: 16px; color: #4b5563;''>شكراً لتسجيلك. خطوة واحدة فقط تفصلك عن الانضمام لمجتمعنا. يرجى تأكيد بريدك الإلكتروني بالضغط على الزر أدناه.</p>" content_en="<p style=''margin: 0 0 16px; font-weight: 700; font-size: 20px; color: #000000;''>Welcome, {{user_name}}!</p><p style=''margin: 0 0 24px; font-size: 16px; color: #4b5563;''>Thanks for signing up. Just one more step: please confirm your email address by clicking the button below.</p>" cta_text="Confirm Email Address" cta_link="{{verification_link}}" }}'),
('Account Approved', 'Your UniShorts Account is Approved!', '{{> base_email_template subject="Account Approved" preheader="Welcome aboard! Your account has been approved." content_ar="<p style=''margin: 0 0 16px; font-weight: 700; font-size: 20px; color: #000000;''>تهانينا، {{user_name}}!</p><p style=''margin: 0 0 24px; font-size: 16px; color: #4b5563;''>تمت الموافقة على حسابك. يمكنك الآن تسجيل الدخول والبدء في استكشاف المنصة.</p>" content_en="<p style=''margin: 0 0 16px; font-weight: 700; font-size: 20px; color: #000000;''>Congratulations, {{user_name}}!</p><p style=''margin: 0 0 24px; font-size: 16px; color: #4b5563;''>Your account has been approved. You can now log in and start exploring.</p>" cta_text="Go to Dashboard" cta_link="{{login_link}}" }}'),
('Account Rejected', 'Update on Your UniShorts Application', '{{> base_email_template subject="Application Update" preheader="An update on your UniShorts account application." content_ar="<p style=''margin: 0 0 16px; font-weight: 700; font-size: 20px; color: #000000;''>مرحباً، {{user_name}}</p><p style=''margin: 0 0 24px; font-size: 16px; color: #4b5563;''>شكراً لاهتمامك بالانضمام. للأسف، لم نتمكن من الموافقة على طلبك في الوقت الحالي. سبب الرفض: {{reason}}</p>" content_en="<p style=''margin: 0 0 16px; font-weight: 700; font-size: 20px; color: #000000;''>Hello, {{user_name}}</p><p style=''margin: 0 0 24px; font-size: 16px; color: #4b5563;''>Thank you for your interest. Unfortunately, we could not approve your application at this time. Reason: {{reason}}</p>" cta_text="Contact Support" cta_link="mailto:support@unishorts.app" }}'),
('Password Reset', 'Reset Your UniShorts Password', '{{> base_email_template subject="Password Reset" preheader="A request was made to reset your password." content_ar="<p style=''margin: 0 0 24px; font-size: 16px; color: #4b5563;''>لقد تلقينا طلباً لإعادة تعيين كلمة المرور الخاصة بك. اضغط على الزر أدناه لإعادة تعيينها. إذا لم تطلب ذلك، يمكنك تجاهل هذا البريد.</p>" content_en="<p style=''margin: 0 0 24px; font-size: 16px; color: #4b5563;''>We received a request to reset your password. Click the button below to proceed. If you did not request this, you can safely ignore this email.</p>" cta_text="Reset Password" cta_link="{{reset_link}}" }}'),
('Password Changed', 'Your UniShorts Password Was Changed', '{{> base_email_template subject="Password Changed" preheader="Your password has been successfully changed." content_ar="<p style=''margin: 0 0 24px; font-size: 16px; color: #4b5563;''>تم تغيير كلمة المرور الخاصة بك بنجاح. إذا لم تقم أنت بهذا التغيير، يرجى تأمين حسابك فوراً.</p>" content_en="<p style=''margin: 0 0 24px; font-size: 16px; color: #4b5563;''>Your password was changed successfully. If you did not make this change, please secure your account immediately.</p>" cta_text="Secure Your Account" cta_link="{{secure_link}}" }}'),
('New Login Alert', 'New Login to Your UniShorts Account', '{{> base_email_template subject="New Login Alert" preheader="A new device has logged into your account." content_en="<p style=''margin: 0 0 16px; font-size: 16px; color: #4b5563;''>We detected a new login to your account:</p><ul style=''padding-left: 20px; color: #4b5563;''><li><strong>Device:</strong> {{device_type}}</li><li><strong>Browser:</strong> {{browser}}</li><li><strong>Location:</strong> {{location}}</li><li><strong>Time:</strong> {{time}}</li></ul><p style=''margin: 16px 0 0; font-size: 16px; color: #4b5563;''>If this was not you, please reset your password immediately.</p>" cta_text="Reset Password" cta_link="{{reset_link}}" }}'),
('Film Submission Confirmation', 'We''ve Received Your Film!', '{{> base_email_template subject="Film Received" preheader="Your film has been submitted for review." content_en="<p style=''margin: 0 0 16px; font-weight: 700; font-size: 20px; color: #000000;''>Thanks for submitting ''{{film_title}}''!</p><p style=''margin: 0 0 24px; font-size: 16px; color: #4b5563;''>We''ve received your film and it is now in our review queue. You can expect to hear back from us within 72 hours. You can check its status on your dashboard.</p>" cta_text="View Dashboard" cta_link="{{dashboard_link}}" }}'),
('Film Approved', 'Your Film is Live!', '{{> base_email_template subject="Film Approved" preheader="Congratulations, your film is now live on UniShorts!" content_en="<p style=''margin: 0 0 16px; font-weight: 700; font-size: 20px; color: #000000;''>Congratulations, {{user_name}}!</p><p style=''margin: 0 0 24px; font-size: 16px; color: #4b5563;''>Your film, ''{{film_title}}'', has been approved and is now live on the platform. Share it with the world!</p>" cta_text="View Your Film" cta_link="{{film_link}}" }}'),
('Film Rejected', 'Update on Your Film Submission', '{{> base_email_template subject="Film Submission Update" preheader="An update on your film submission." content_en="<p style=''margin: 0 0 16px; font-weight: 700; font-size: 20px; color: #000000;''>Update on ''{{film_title}}''</p><p style=''margin: 0 0 24px; font-size: 16px; color: #4b5563;''>Thank you for your submission. After careful review, we were unable to approve your film at this time for the following reason: {{reason}}</p><p style=''margin: 16px 0 0; font-size: 16px; color: #4b5563;''>We encourage you to make adjustments and resubmit.</p>" cta_text="Go to Dashboard" cta_link="{{dashboard_link}}" }}'),
('Platform Announcement', '{{subject}}', '{{> base_email_template subject="{{subject}}" preheader="{{preheader}}" content_en="{{content}}" cta_text="{{cta_text}}" cta_link="{{cta_link}}" }}');