// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://reqylowdlhhdgoetcfdg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlcXlsb3dkbGhoZGdvZXRjZmRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMzc3MjksImV4cCI6MjA2NzgxMzcyOX0.2tRtRmPJVHWF-3Ra1_AAJJbH9yNGMCNwELNvsQRGwR4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);